micronaut:
  application:
    name: relatorioService
  server:
    port: 8082

kafka:
  bootstrap:
    servers: kafka-server:9092

mongodb:
  uri: 'mongodb://root:123@ms-mongo:27017/admin'

consul:
  client:
    registration:
      enabled: true
    defaultZone: "ms-consul:8500"